### ISSUE TITLE
Try async-proxy module

### ISSUE THREAD

**Issue by BlackGlory** [developit/workerize#1]
This project is very similar to my [worker-sandbox](https://github.com/BlackGlory/worker-sandbox), so I think you probably can use [async-proxy](https://github.com/BlackGlory/async-proxy) module to make the code look clearer.

**Comment by developit** [comment]
Hmm - that seems to rely on Reflect, and pull in quite a lot of polyfills from babel-polyfill. Workerize is intended to be a bare-minimum solution and most of the code is just setting up RPC.
