### ISSUE TITLE
React native support?

### ISSUE THREAD

**Issue by xzilja** [developit/workerize#2]
Hi, wanted to check if there are any difficulties when using workerize with react native? There are solutions that achieve it i.e https://github.com/austinksmith/Hamsters.js But as always your api is much cleaner and minimal.

**Comment by developit** [comment]
It should work with [react-native-workers](https://github.com/devfd/react-native-workers):

```js
import { Worker } from 'react-native-workers'
import workerize from 'workerize'
window.Worker = Worker
workerize( () => {
  export function foo() {
    return 1
  }
})
```

**Comment by xzilja** [comment]
Thank you, quickly tested this and seems to be working good.
